#! /usr/bin/python3

from os import listdir
from markdown import markdown


header = """# 呂廣振的推特

我把靈感記錄在這裡。

"""


index_path = "./index.md"


def get_markdown_file_paths():
    for path in listdir("./"):
        if path != "index.md" and path.endswith(".md"):
            yield path


def main():
    index = open(index_path, 'w')
    index.write(header)
    ls = []
    for p in get_markdown_file_paths():
        f = open(p)
        date = f.readline()
        content = f.read()
        ls.append((date, markdown(date + content)))
    ls.sort(reverse=True)
    for _, md in ls:
        index.write("<article>")
        index.write(md)
        index.write("</article>")
    index.close()
    return

main()
